# Generated by Django 3.0.4 on 2020-11-02 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20201101_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('questioncategory', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Query')),
            ],
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
