# Generated by Django 3.0.4 on 2020-11-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_auto_20201102_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='questioncategory',
        ),
    ]
