# Generated by Django 3.0.4 on 2020-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_auto_20201118_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
